### ISSUE TITLE
Ti SDK 8.2.0 iOS 13 Problem

### ISSUE THREAD

**Issue by nascado** [appcelerator-modules/ti.barcode#113]
When compiling an iOS app with the latest ti.barcode 2.0.4 and  with Ti SDK 8.2.0 / iOS 13 the overlay moves down about 50 pix. Can Anyone help pease.

**Comment by fabiomlferreira** [comment]
I have exactly the same problem. Any solution?

**Comment by fabiomlferreira** [comment]
@nascado did you find any solution?

**Comment by nascado** [comment]
﻿Not yet, I’m still waiting for a new version. 

Best regards, 
Marco Huppertz

**Comment by checknique** [comment]
I have this problem too. It pushes my bottom nav bar out of view of the user.

**Comment by m1ga** [comment]
isn't that a problem that was fixed in the titanium SDK 8.2.1?

**Comment by nascado** [comment]
The problem is still there with:
Xcode 11.1  (MacOS 10.4.6 or 10.15)
Titanium SDK 8.2.1
iPhone 11 v. 13.1
ti.barcode latest = 2.0.4

**Comment by checknique** [comment]
Just tested. 
+1 Problem persists with Titanium SDK 8.2.1.

**Comment by checknique** [comment]
Need ability to handle Modal Windows for module in 13?
https://jira.appcelerator.org/browse/TIMOB-27169

**Comment by PietroGranati** [comment]
Found something:
https://medium.com/@hacknicity/view-controller-presentation-changes-in-ios-13-ac8c901ebc4e

**Comment by PietroGranati** [comment]
And I found the solution here, I'm trying to implementate

**Comment by SquirrelMobile** [comment]
This is the module fixed : 
[5.0.0.zip](https://github.com/appcelerator-modules/ti.barcode/files/4292801/5.0.0.zip)

**Comment by SquirrelMobile** [comment]
PR here : https://github.com/appcelerator-modules/ti.barcode/pull/121

**Comment by PietroGranati** [comment]
Thanks!

**Comment by checknique** [comment]
> This is the module fixed :
> [5.0.0.zip](https://github.com/appcelerator-modules/ti.barcode/files/4292801/5.0.0.zip)

I really appreciate you putting this together. However, I don't think I'm using it correctly perhaps? I imported it and built my app but I'm still seeing the modal/stacked windows. Is there something else I need to do? Thanks!

**Comment by ScottKaye** [comment]
> > This is the module fixed :
> > [5.0.0.zip](https://github.com/appcelerator-modules/ti.barcode/files/4292801/5.0.0.zip)
> 
> I really appreciate you putting this together. However, I don't think I'm using it correctly perhaps? I imported it and built my app but I'm still seeing the modal/stacked windows. Is there something else I need to do? Thanks!

Same here unfortunately.  @SquirrelMobile I see the fix is just an attribute, but do you know if there's anything else to try?

Right now I'm having to resort to drawing a black rectangle at the top of my view before rendering the barcode scanner, to cover up the old view.

**Comment by m1ga** [comment]
@ScottKaye which Ti SDK are you using? Also: https://github.com/appcelerator-modules/ti.barcode/releases/tag/v5.0.0-iphone is the latest module

**Comment by ScottKaye** [comment]
Hi @m1ga, I'm using 8.3.0GA, which I can't easily update due to testing constraints in my organization.  I am using v5.0.0 of the iOS module, however.

**Comment by m1ga** [comment]
I see, perhaps as a workaround you could use https://github.com/mikefogg/SquareCamera ? It is a normal view and can scan QR and barcodes too.

**Comment by nicolomonili** [comment]
Tested on SDK **9.0.3.GA** with [v5.0.0](https://github.com/appcelerator-modules/ti.barcode/releases/tag/v5.0.0-iphone) . The window does not open in **fullscreen**.
